给定一个 m x n 的矩阵，如果一个元素为 0，则将其所在行和列的所有元素都设为 0。请使用原地算法。

示例 1:

输入: 
[
  [1,1,1],
  [1,0,1],
  [1,1,1]
]
输出: 
[
  [1,0,1],
  [0,0,0],
  [1,0,1]
]

In [126]:
def setZeroes(matrix) -> None:
    """
    Do not return anything, modify matrix in-place instead.
    """
    import numpy as np
    mat = np.array(matrix)
    index = np.argwhere(mat == 0)
    for i in range(len(index)):
        mat[index[i][0],:] = 0 
        mat[:,index[i][1]] = 0
        
    matrix = mat.tolist()


a = [[1,1,1],[1,0,1],[1,1,0]]


t = setZeroes(a)
a[:][1] = 0
print(a)

[[1, 1, 1], [1, 0, 1], [1, 1, 0]]


In [112]:
import numpy as np
mat = np.array(a)
index = np.argwhere(mat == 0)
print(index)

for i in range(len(index)):
    mat[index[i][0],:] = 0 
    mat[:,index[i][1]] = 0
    
# mat = mat.tolist()
print(' - - - ')
print(mat)



[[1 1]
 [2 2]]
 - - - 
[[1 0 0]
 [0 0 0]
 [0 0 0]]
