994. 腐烂的橘子
在给定的网格中，每个单元格可以有以下三个值之一：

值 0 代表空单元格；
值 1 代表新鲜橘子；
值 2 代表腐烂的橘子。
每分钟，任何与腐烂的橘子（在 4 个正方向上）相邻的新鲜橘子都会腐烂。

返回直到单元格中没有新鲜橘子为止所必须经过的最小分钟数。如果不可能，返回 -1。
输入：[[2,1,1],[1,1,0],[0,1,1]]
输出：4

输入：[[2,1,1],[0,1,1],[1,0,1]]
输出：-1
解释：左下角的橘子（第 2 行， 第 0 列）永远不会腐烂，因为腐烂只会发生在 4 个正向上。

输入：[[0,2]]
输出：0
解释：因为 0 分钟时已经没有新鲜橘子了，所以答案就是 0 。

In [19]:
def orangesRotting(grid) :
    
    return grid


grid = [[2,1,1],[0,1,1],[1,0,1]]
t = orangesRotting(grid)
print(t)

[[2, 1, 1], [0, 1, 1], [1, 0, 1]]


In [777]:
grid = [[2,1,1],[0,1,1],[1,0,1]]

def listRotting2(l):
    for i in range(len(l)-1):
        if l[i:i+2] == [1, 2]:
            l[i] = 2
        elif l[i:i+2] == [2, 1]:
            l[i+1] = 2
      
# print(grid[0])        
# listRotting(grid[0])
b = [i[0] for i in grid]
# print(b)
    #if 2 in l:
    #print(l.index(2))


import numpy as np
data = np.array(grid)
print(data)##

def listStepRotting(l):
    for i in range(len(l) - 1):
        if all(l[i:i+2] == np.array([1, 2])):
            l[i] = 2
            break
        elif all(l[i:i+2] == np.array([2, 1])):
            l[i+1] = 2
            break
step = 0
l = np.array([2,1,1,1])        
tmp = np.array([3])
flag = True
print(l)

while('2 1' in str(l)):

    listStepRotting(l)
    step+=1
    
print(step)    


print('/////////')
print(data)
# while
listStepRotting([])

[[2 1 1]
 [0 1 1]
 [1 0 1]]
[2 1 1 1]
3
/////////
[[2 1 1]
 [0 1 1]
 [1 0 1]]
